/**
 * Style Dictionary v4 — token build config
 *
 * Input:  tokens/tokens.json  (W3C DTCG format, edited by hand or by Tokens Studio)
 * Output: tokens/generated/tokens.css  (CSS custom properties, :root {})
 *
 * Run:  npm run build:tokens   (from the app/ directory)
 *
 * CSS variable names are derived by joining JSON key path segments with hyphens.
 * E.g.  color > brand > purple-light  →  --color-brand-purple-light
 *
 * ⚠️  Do NOT edit tokens/generated/* directly — those files are auto-generated.
 *    Edit tokens/tokens.json or the source CSS token files instead.
 */

import StyleDictionary from "style-dictionary";

// ── Custom transform: keep dimension values as-is (no px → rem conversion) ───
StyleDictionary.registerTransform({
  name: "size/px-passthrough",
  type: "value",
  filter: (token) => token.$type === "dimension",
  transform: (token) => token.$value,
});

// ── Custom transform: shadow → CSS box-shadow string ─────────────────────────
StyleDictionary.registerTransform({
  name: "shadow/css",
  type: "value",
  filter: (token) => token.$type === "shadow",
  transform: (token) => {
    const v = token.$value;
    if (typeof v === "string") return v; // "none"
    const { offsetX, offsetY, blur, spread, color } = v;
    return `${offsetX} ${offsetY} ${blur} ${spread} ${color}`;
  },
});

// ── Custom transform: fontFamily array → CSS font-family string ───────────────
StyleDictionary.registerTransform({
  name: "fontFamily/css",
  type: "value",
  filter: (token) => token.$type === "fontFamily",
  transform: (token) => {
    const v = token.$value;
    if (Array.isArray(v)) {
      return v.map((f) => (f.includes(" ") ? `"${f}"` : f)).join(", ");
    }
    return v;
  },
});

// ── Custom format: output :root {} block ──────────────────────────────────────
StyleDictionary.registerFormat({
  name: "css/root-variables",
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens
      // Skip composite types (typography) — they expand into individual CSS props elsewhere
      .filter((t) => t.$type !== "typography")
      .map((token) => {
        const name = token.name; // already kebab-cased by name/kebab transform
        const value = token.value ?? token.$value;
        return `  --${name}: ${value};`;
      });

    return [
      "/**",
      " * Generated by Style Dictionary — DO NOT EDIT",
      " * Source: tokens/tokens.json",
      " * Run `npm run build:tokens` to regenerate.",
      " */",
      "",
      ":root {",
      ...lines,
      "}",
      "",
    ].join("\n");
  },
});

// ── Config ────────────────────────────────────────────────────────────────────

const sd = new StyleDictionary({
  source: ["tokens/tokens.json"],

  platforms: {
    css: {
      transforms: [
        "attribute/cti",
        "name/kebab",
        "color/css",
        "size/px-passthrough",
        "shadow/css",
        "fontFamily/css",
      ],
      buildPath: "tokens/generated/",
      files: [
        {
          destination: "tokens.css",
          format: "css/root-variables",
        },
      ],
    },

    // JSON export — used by Tokens Studio for round-tripping
    json: {
      transforms: ["attribute/cti", "name/kebab"],
      buildPath: "tokens/generated/",
      files: [
        {
          destination: "tokens.json",
          format: "json/nested",
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();
console.log("\n✅  Token build complete → tokens/generated/");
