import type { Account, AccountDetail } from "@/lib/types";

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);

export const mockAccounts: Account[] = [
  {
    id: "walmart-corp",
    name: "Acme Co",
    type: "corporate",
    crmAccountType: "distributor",
    assignedInitial: "J",
    taskCount: 0,
    address: "702 SW 8th St",
    city: "Bentonville",
    state: "AR",
    distanceMiles: 56.7,
    lastVisited: daysAgo(3),
    childCount: 14,
    crmId: "SF-001",
    healthScore: 82,
  },
  {
    id: "walmart-cedar-city",
    name: "Branch of Acme Co",
    type: "branch",
    crmAccountType: "shipped-to",
    assignedInitial: "J",
    taskCount: 5,
    openOpportunities: 1,
    address: "1300 S Main St",
    city: "Cedar City",
    state: "UT",
    distanceMiles: 56.7,
    lastVisited: daysAgo(3),
    childCount: 7,
    parentId: "walmart-corp",
    crmId: "SF-002",
    healthScore: 78,
  },
  {
    id: "jacks-tire-elko",
    name: "Jack's Tire & Oil",
    type: "standalone",
    crmAccountType: "sold-to",
    assignedInitial: "M",
    taskCount: 2,
    openOpportunities: 3,
    address: "742 Idaho St",
    city: "Elko",
    state: "NV",
    distanceMiles: 13.5,
    lastVisited: daysAgo(14),
    contactName: "Marcus Webb",
    contactTitle: "General Manager",
    crmId: "SF-003",
    healthScore: 65,
  },
  {
    id: "profleet-corp",
    name: "ProFleet Maintenance",
    type: "corporate",
    crmAccountType: "distributor",
    assignedInitial: "S",
    taskCount: 0,
    city: "Phoenix",
    state: "AZ",
    distanceMiles: 146,
    lastVisited: daysAgo(6),
    childCount: 14,
    crmId: "SF-004",
    healthScore: 74,
  },
  {
    id: "profleet-glendale-1",
    name: "ProFleet Maintenance",
    type: "branch",
    crmAccountType: "sold-to",
    assignedInitial: "S",
    taskCount: 0,
    city: "Glendale",
    state: "AZ",
    distanceMiles: 0.75,
    lastVisited: daysAgo(90),
    parentId: "profleet-corp",
    crmId: "SF-005",
    healthScore: 55,
  },
  {
    id: "profleet-flagstaff",
    name: "ProFleet Maintenance Store",
    type: "branch",
    crmAccountType: "shipped-to",
    assignedInitial: "A",
    taskCount: 0,
    city: "Flagstaff",
    state: "AZ",
    distanceMiles: 845,
    lastVisited: daysAgo(21),
    parentId: "profleet-corp",
    crmId: "SF-006",
    healthScore: 70,
  },
  {
    id: "profleet-glendale-2",
    name: "ProFleet Maintenance Store",
    type: "branch",
    crmAccountType: "sold-to",
    assignedInitial: "S",
    taskCount: 1,
    openOpportunities: 1,
    address: "5850 W Bell Rd",
    city: "Glendale",
    state: "AZ",
    distanceMiles: 3.5,
    lastVisited: new Date(),
    parentId: "profleet-corp",
    crmId: "SF-007",
    healthScore: 88,
  },
  {
    id: "profleet-tucson",
    name: "ProFleet Maintenance Store",
    type: "standalone",
    halosightType: "prospect",
    assignedInitial: "A",
    taskCount: 0,
    city: "Tucson",
    state: "AZ",
    distanceMiles: 56.7,
    lastVisited: daysAgo(14),
    healthScore: 72,
  },
  {
    id: "innovative-tech-tucson",
    name: "Innovative Tech",
    type: "standalone",
    halosightType: "prospect",
    assignedInitial: "M",
    taskCount: 7,
    openOpportunities: 2,
    address: "4820 E Grant Rd",
    city: "Tucson",
    state: "AZ",
    distanceMiles: 1.4,
    lastVisited: daysAgo(30),
    contactName: "Sandra Perez",
    contactTitle: "Operations Director",
    healthScore: 60,
  },
  {
    id: "saddleback-fleet",
    name: "Saddleback Fleet Services",
    type: "standalone",
    halosightType: "prospect",
    assignedInitial: "N",
    taskCount: 0,
    address: "2140 S Power Rd",
    city: "Mesa",
    state: "AZ",
    distanceMiles: 4.2,
    lastVisited: daysAgo(2),
    contactName: "Derek Carlisle",
    contactTitle: "Facilities Manager",
  },
  {
    id: "riverbend-collision",
    name: "Riverbend Collision",
    type: "standalone",
    halosightType: "prospect",
    assignedInitial: "J",
    taskCount: 0,
    city: "St George",
    state: "UT",
    distanceMiles: 241,
    lastVisited: daysAgo(365),
    contactName: "Tom Hadley",
    contactTitle: "Owner",
    healthScore: 30,
  },
  {
    id: "southwestern-consolidated",
    name: "Southwestern Consolidated Fleet Management & Distribution Services, LLC",
    type: "corporate",
    crmAccountType: "distributor",
    assignedInitial: "N",
    taskCount: 2,
    openOpportunities: 1,
    address: "4801 N Central Ave",
    city: "Phoenix",
    state: "AZ",
    distanceMiles: 8.3,
    lastVisited: daysAgo(14),
    contactName: "Patricia Delgado",
    contactTitle: "VP of Fleet Operations",
    crmId: "SF-099",
    healthScore: 71,
  },
];

const future = (month: number, day: number) => new Date(2026, month - 1, day);

const at = (daysBack: number, h: number, m: number) => {
  const d = daysAgo(daysBack);
  d.setHours(h, m, 0, 0);
  return d;
};

export const mockAccountDetails: Record<string, AccountDetail> = {
  "jacks-tire-elko": {
    ...mockAccounts[2],
    relatedAccountCount: 3,
    lastVisitSummary:
      "Visited 2 weeks ago. Marcus walked me through a few recurring issues with their current supplier — lead times and inconsistent part quality. They're open to switching if we can demonstrate reliability.",
    ideasForThisTime: [
      "Ask about upcoming seasonal demand",
      "Explore additional product/service needs",
      "Identify front-line decision makers",
      "Confirm any pain points before they grow",
    ],
    actionItems: [
      { id: "ja-t1", title: "Send Q2 pricing update",        dueDate: future(6, 5),  status: "open", originActivity: "Follow-Up Call",      originActivityId: "ja-6" },
      { id: "ja-t2", title: "On-site training for new team", dueDate: null,          status: "open", originActivity: "Client Presentation",  originActivityId: "ja-4" },
      { id: "ja-t3", title: "Provide weekly updates",        dueDate: future(6, 20), status: "open", originActivity: "Client Presentation",  originActivityId: "ja-4" },
      { id: "ja-t4", title: "Investigate account",           dueDate: future(6, 12), status: "open", originActivity: "Market Research",      originActivityId: "ja-3" },
      { id: "ja-t5", title: "Send intro deck",               dueDate: daysAgo(3),    status: "done", originActivity: "Discovery Call",       originActivityId: "ja-1" },
      { id: "ja-t6", title: "Confirm meeting with Marcus",   dueDate: daysAgo(7),    status: "done", originActivity: "Discovery Call",       originActivityId: "ja-1" },
    ],
    recentActivity: [
      {
        id: "ja-1", accountId: "jacks-tire-elko", date: at(9, 15, 46), type: "call", title: "Marcus outlined supplier pain points and confirmed openness to switching",
        summary: "Initial discovery with Jack's Tire and Oil to understand their platform upgrade needs and timeline.",
        durationMinutes: 35, hasTranscript: true, repName: "Jordan Mills",
        aiSummary: {
          title: "Marcus outlined supplier pain points and confirmed openness to switching vendors",
          tldr: "Marcus walked through recurring issues with their current supplier — late deliveries and inconsistent part quality are causing real floor-level slowdowns. He confirmed they're open to switching if reliability can be demonstrated before Q3.",
          keyPoints: [
            "**Late deliveries** from the current supplier are creating floor slowdowns — Marcus flagged this as the **primary pain point**.",
            "Part quality has been **inconsistent**, leading to returns and rework that erode margin.",
            "Marcus confirmed they have **budget available** and a decision timeline tied to Q3 peak season.",
            "He wants to see a **concrete delivery SLA** before moving forward — proximity of our distribution hub was well received.",
          ],
        },
      },
      { id: "ja-2", accountId: "jacks-tire-elko", date: at(9, 15, 46), type: "call",  title: "Intro call on Jack's upgrade timeline and current workflow gaps", summary: "Initial discovery with Jack's Tire and Oil to understand their platform upgrade needs and timeline.", durationMinutes: 35,  hasTranscript: true,  repName: "Jordan Mills" },
      {
        id: "ja-3", accountId: "jacks-tire-elko", date: at(4, 11, 0), type: "visit", title: "Competitive pricing review — our turnaround time flagged as a key differentiator",
        summary: "Reviewed competitor platforms to identify feature gaps and opportunities for differentiation.",
        durationMinutes: 80, hasTranscript: false, repName: "Jordan Mills",
        aiSummary: {
          title: "Competitive landscape review revealed clear differentiation opportunities for Q3 pitch",
          tldr: "Reviewed three competitor offerings side-by-side with the Jack's team. Our turnaround time and regional coverage stood out as clear differentiators — their current vendor scores poorly on both.",
          keyPoints: [
            "Competitors were evaluated on **turnaround time**, **part quality**, and **regional availability** — we lead on all three.",
            "The team noted that their current vendor has a **5–7 day average lead time** vs. our 2-day SLA.",
            "Marcus specifically called out **regional coverage** as a deciding factor — our Cedar City hub is a meaningful advantage.",
            "The team is now **actively building an internal case** to switch — procurement involvement expected next week.",
          ],
        },
      },
      { id: "ja-4", accountId: "jacks-tire-elko", date: at(4, 11, 0),  type: "visit", title: "Walked Marcus through the proposal — strong interest, a few questions on SLA terms", summary: "Presented initial project proposal and received feedback from Jack's Tire and Oil stakeholders.", durationMinutes: 45,  hasTranscript: true,  repName: "Jordan Mills" },
      { id: "ja-5", accountId: "jacks-tire-elko", date: at(2, 14, 0),  type: "visit", title: "Internal prep session on tech requirements and Jack's onboarding timeline", summary: "Collaborated with design and engineering teams to outline technical requirements and wireframes.", durationMinutes: 90,  hasTranscript: false, repName: "Jordan Mills" },
      { id: "ja-6", accountId: "jacks-tire-elko", date: at(1, 9, 30),  type: "call",  title: "Marcus confirmed budget approved — ready to move to contract stage", summary: "Checked in on proposal status. Marcus confirmed internal budget approval. Ready to proceed.", durationMinutes: 18,  hasTranscript: true,  repName: "Jordan Mills" },
    ],
  },
  "walmart-cedar-city": {
    ...mockAccounts[1],
    relatedAccountCount: 7,
    lastVisitSummary:
      "Visited 3 days ago. Spoke with the store ops lead about ongoing friction with their current parts supplier — late deliveries are causing floor slowdowns. They're motivated to find a better solution before Q3 peak season hits.",
    ideasForThisTime: [
      "Come with a concrete delivery SLA to address their lead time concern",
      "Ask about Q3 seasonal volume to size the opportunity",
      "Find out who else is involved in the vendor decision",
      "Mention the Cedar City distribution hub — proximity is a differentiator",
    ],
    actionItems: [
      { id: "wc-t1", title: "Send pricing recap",              dueDate: future(6, 4),  status: "open", originActivity: "Discovery Call",      originActivityId: "wc-2" },
      { id: "wc-t2", title: "Follow up with procurement",      dueDate: future(6, 8),  status: "open", originActivity: "Discovery Call",      originActivityId: "wc-2" },
      { id: "wc-t3", title: "Confirm delivery SLA in writing", dueDate: future(6, 15), status: "open", originActivity: "Ops Check-In",        originActivityId: "wc-1" },
      { id: "wc-t4", title: "Schedule Q3 planning call",       dueDate: null,          status: "open", originActivity: "Ops Check-In",        originActivityId: "wc-1" },
      { id: "wc-t5", title: "Send updated contract draft",     dueDate: future(6, 20), status: "open", originActivity: "Contract Discussion", originActivityId: "wc-6" },
    ],
    recentActivity: [
      {
        id: "wc-1", accountId: "walmart-cedar-city", date: at(3, 14, 30), type: "visit", title: "Ops lead flagged late deliveries causing floor slowdowns — strong motivation to switch before Q3",
        summary: "Spoke with ops lead about supplier friction. Late deliveries causing floor slowdowns ahead of Q3. Strong motivation to switch.",
        durationMinutes: 40, hasTranscript: true, repName: "Jordan Mills",
        aiSummary: {
          title: "Ops lead confirmed supplier frustration and signaled strong motivation to switch before Q3",
          tldr: "The ops lead walked through the impact of their current supplier's delays on floor productivity. With Q3 peak season approaching, they're actively looking for a replacement and want to move fast.",
          keyPoints: [
            "**Late deliveries** are the core issue — the ops lead described floor slowdowns happening **2–3 times per week**.",
            "The team has already started **documenting failures** from their current supplier as part of an internal case to switch.",
            "They need a solution in place **before July** — Q3 peak season is the hard deadline driving urgency.",
            "The ops lead confirmed he has **sign-off authority** up to a certain spend threshold — procurement only needed above that.",
          ],
        },
      },
      {
        id: "wc-2", accountId: "walmart-cedar-city", date: at(3, 15, 46), type: "call", title: "Pricing structure clarified — procurement contact being looped in for sign-off",
        summary: "Followed up same day to clarify pricing structure and confirm next steps. Manager looping in their procurement contact.",
        durationMinutes: 18, hasTranscript: true, repName: "Jordan Mills",
        aiSummary: {
          title: "Pricing structure clarified — procurement contact being looped in for final sign-off",
          tldr: "Quick follow-up call to walk through the pricing tiers after the earlier ops meeting. The manager confirmed interest and said she's looping in their procurement contact to review the SLA terms.",
          keyPoints: [
            "Manager confirmed the **standard tier pricing** aligns with their budget — no major concerns raised.",
            "**Procurement contact** (name TBD) will be looped in — manager expects to make intro by end of week.",
            "She asked for a **one-pager** summarizing delivery SLA and pricing for the internal review.",
            "Next step is a **three-way call** with ops lead, manager, and procurement — aiming for early next week.",
          ],
        },
      },
      { id: "wc-3", accountId: "walmart-cedar-city", date: at(10, 11, 0),  type: "visit", title: "Reviewed competitor service levels — our proximity advantage resonated with the team", summary: "Reviewed competitor service levels with the store manager. Our proximity advantage resonated strongly.", durationMinutes: 80, hasTranscript: false, repName: "Jordan Mills" },
      { id: "wc-4", accountId: "walmart-cedar-city", date: at(10, 13, 30), type: "visit", title: "Walked through service tiers and delivery SLAs — procurement contact now looped in", summary: "Presented service tier options and delivery SLA guarantees. Positive reception — procurement contact now involved.", durationMinutes: 55, hasTranscript: true,  repName: "Jordan Mills" },
      { id: "wc-5", accountId: "walmart-cedar-city", date: at(18, 9, 0),   type: "visit", title: "Walked ops and floor leads through implementation logistics and onboarding timeline", summary: "Walked through implementation logistics with ops and floor leads. Outlined onboarding timeline and support contacts.", durationMinutes: 90, hasTranscript: false, repName: "Jordan Mills" },
      { id: "wc-6", accountId: "walmart-cedar-city", date: at(25, 10, 15), type: "call",  title: "Reviewed contract terms by phone — a few line items flagged for revision", summary: "Reviewed initial contract terms over the phone. A few line items flagged for revision — following up with updated draft.", durationMinutes: 28, hasTranscript: false, repName: "Jordan Mills" },
      { id: "wc-7", accountId: "walmart-cedar-city", date: at(33, 14, 0),  type: "visit", title: "Store manager and two department heads aligned — moving forward pending budget approval", summary: "Met with store manager and two department heads. All aligned on moving forward pending final budget approval.", durationMinutes: 60, hasTranscript: true,  repName: "Jordan Mills" },
      { id: "wc-8", accountId: "walmart-cedar-city", date: at(47, 11, 30), type: "call",  title: "Cold outreach intro — manager flagged frustration with current supplier right away", summary: "Cold outreach call — introduced ourselves and gauged interest. Manager expressed frustration with current supplier.", durationMinutes: 14, hasTranscript: false, repName: "Jordan Mills" },
    ],
  },
  "walmart-corp": {
    ...mockAccounts[0],
    relatedAccountCount: 24,
    lastVisitSummary:
      "Visited 3 days ago. Conversation focused on Q2 supply chain concerns. Tom mentioned potential for an expanded order next quarter and flagged some dissatisfaction with current turnaround times.",
    ideasForThisTime: [
      "Ask about upcoming seasonal demand",
      "Explore additional product/service needs",
      "Identify front-line decision makers",
      "Confirm any pain points before they grow",
    ],
    actionItems: [
      { id: "wm-t1", title: "Send Q2 pricing update", dueDate: future(6, 5), status: "open", originActivity: "Quarterly Review", originActivityId: "wm-1", description: "Dave asked for a revised pricing sheet reflecting the higher brake pad volumes they're now projecting. He wants to compare our Q2 rates against what their current supplier quoted before the back-order issues started." },
      { id: "wm-t2", title: "Schedule executive review", dueDate: future(6, 18), status: "open", originActivity: "Quarterly Review", originActivityId: "wm-1", description: "Dave flagged that the ops director wants to be looped in before any vendor change is formalized. Setting up a 30-minute intro to walk through our reliability track record and distribution coverage." },
      { id: "wm-t3", title: "Share turnaround SLA doc", dueDate: future(6, 10), status: "open", originActivity: "Quarterly Review", originActivityId: "wm-1", description: "Acme Co's biggest concern is lead time consistency. Dave specifically asked for a written SLA they can bring to procurement — needs to include restocking timelines and back-order escalation commitments." },
      { id: "wm-t4", title: "Send Q1 recap report",       dueDate: daysAgo(5),    status: "done", originActivity: "Routine Check-In", originActivityId: "wm-2" },
      { id: "wm-t5", title: "Confirm Q2 site visit",      dueDate: daysAgo(10),   status: "done", originActivity: "Routine Check-In", originActivityId: "wm-2" },
    ],
    recentActivity: [
      {
        id: "wm-1", accountId: "walmart-corp", date: at(3, 14, 20), type: "visit", title: "Brake pad supply gaps discussed — Dave flagged expanded order potential for Q3",
        summary: "Discussed Q2 supply chain concerns. Tom mentioned potential for expanded order next quarter.",
        durationMinutes: 55, hasTranscript: true, repName: "Jordan Mills",
        aiSummary: {
          title: "Brake pad demand surge creating supply pressure — Dave signaled expanded order potential for Q3",
          tldr: "Sat down with Dave Mercer and the Acme Co fleet ops team to review Q2 performance and walk through an emerging brake pad shortage across their service locations. Acme has seen faster-than-expected wear rates on their mixed fleet this cycle, and their current supplier has been slow to respond. The conversation shifted toward what a deeper, more reliable supply partnership could look like heading into Q3.",
          keyPoints: [
            "**Brake pad wear rates** across the fleet are running **15–20% higher** than projected — ops team is feeling the pressure at multiple locations.",
            "Current supplier has had **two back-order incidents** in the past 60 days, causing unplanned downtime on the floor.",
            "Dave flagged Q3 as a **high-stakes window** — seasonal volume uptick means the fleet can't afford parts slowdowns.",
            "He mentioned a **potential volume expansion** if we can demonstrate consistent availability and fast restocking turnaround.",
            "Team is open to exploring a **vendor-managed inventory model** to reduce their own stock overhead.",
          ],
        },
      },
      { id: "wm-2", accountId: "walmart-corp", date: at(17, 10, 0),  type: "visit", title: "Checked in on service satisfaction — relationship in good standing, nothing new flagged", summary: "Reviewed current service satisfaction. No new opportunities surfaced — relationship in good standing.", durationMinutes: 30,  hasTranscript: true,  repName: "Jordan Mills" },
      { id: "wm-3", accountId: "walmart-corp", date: at(31, 9, 15),  type: "call",  title: "Followed up on the delayed shipment — issue resolved, Dave satisfied with the outcome", summary: "Follow-up call on delayed shipment. Issue resolved. Customer satisfied with resolution.", durationMinutes: 12,  hasTranscript: false, repName: "Jordan Mills" },
      { id: "wm-4", accountId: "walmart-corp", date: at(45, 13, 30), type: "visit", title: "Walked through premium service tier options — strong interest, needs procurement sign-off", summary: "Walked through new service tier options. Strong interest in the premium package — needs sign-off from procurement.", durationMinutes: 70, hasTranscript: true,  repName: "Sarah Kim" },
      { id: "wm-5", accountId: "walmart-corp", date: at(60, 11, 0),  type: "email", title: "Sent annual contract renewal terms — waiting on their legal team to review", summary: "Sent over renewal terms for annual contract. Awaiting internal review from their legal team.", durationMinutes: 8,   hasTranscript: false, repName: "Jordan Mills" },
    ],
  },
  "profleet-corp": {
    ...mockAccounts[3],
    relatedAccountCount: 14,
    lastVisitSummary:
      "Visited 6 days ago. Good conversation with ops leadership about upcoming Q3 fleet expansion. Budget has been earmarked — they want a formal proposal by end of month.",
    ideasForThisTime: [
      "Deliver formal Q3 fleet expansion proposal",
      "Introduce volume discount options",
      "Discuss service contract upgrade path",
      "Check in on satisfaction across branch locations",
    ],
    actionItems: [
      { id: "pf-t1", title: "Submit Q3 fleet proposal",      dueDate: future(5, 30), status: "open", originActivity: "Leadership Check-In", originActivityId: "pf-1" },
      { id: "pf-t2", title: "Prepare volume discount sheet",  dueDate: future(6, 7),  status: "open", originActivity: "Leadership Check-In", originActivityId: "pf-1" },
      { id: "pf-t3", title: "Check in on Glendale 1 branch",  dueDate: future(6, 14), status: "open", originActivity: "Annual Strategy",      originActivityId: "pf-3" },
      { id: "pf-t4", title: "Send annual contract renewal",   dueDate: daysAgo(4),    status: "done", originActivity: "Annual Strategy",      originActivityId: "pf-3" },
    ],
    recentActivity: [
      { id: "pf-1", accountId: "profleet-corp", date: at(6, 10, 30),  type: "visit", title: "Ops leadership confirmed Q3 fleet expansion budget — formal proposal requested by end of month", summary: "Met with ops leadership re: Q3 fleet expansion. Budget confirmed. Formal proposal requested.", durationMinutes: 60,  hasTranscript: true,  repName: "Jordan Mills" },
      { id: "pf-2", accountId: "profleet-corp", date: at(20, 14, 0),  type: "call",  title: "Scoped the Q3 proposal and landed on pricing structure — key decision-makers identified", summary: "Aligned on scope and pricing structure for the Q3 proposal. Key decision-makers identified.", durationMinutes: 40,  hasTranscript: false, repName: "Sarah Kim" },
      { id: "pf-3", accountId: "profleet-corp", date: at(34, 9, 0),   type: "visit", title: "Year-in-review with leadership — two underperforming branches flagged for follow-up", summary: "Year-in-review meeting. Reviewed account health, flagged two underperforming branches for follow-up.", durationMinutes: 90, hasTranscript: true,  repName: "Sarah Kim" },
      { id: "pf-4", accountId: "profleet-corp", date: at(50, 11, 45), type: "call",  title: "Handled Glendale 1 parts delivery complaint — resolved same day", summary: "Handled complaint about delayed parts delivery at Glendale 1 location. Resolved same day.", durationMinutes: 22,  hasTranscript: false, repName: "Sarah Kim" },
    ],
  },
  "profleet-glendale-2": {
    ...mockAccounts[6],
    relatedAccountCount: 14,
    lastVisitSummary:
      "Visited today. Discussed new fleet acquisition coming in Q3. Manager hinted at budget availability for an expanded service contract — strong opportunity to upsell.",
    ideasForThisTime: [
      "Follow up on Q3 fleet expansion proposal",
      "Introduce premium service tier options",
      "Ask about satisfaction with current turnaround times",
      "Check on status of pending invoice from last month",
    ],
    actionItems: [
      { id: "pg-t1", title: "Send expanded contract proposal", dueDate: future(6, 3),  status: "open", originActivity: "Fleet Expansion",   originActivityId: "pg-1" },
      { id: "pg-t2", title: "Resolve pending invoice",         dueDate: future(5, 30), status: "open", originActivity: "Invoice Follow-Up", originActivityId: "pg-2" },
    ],
    recentActivity: [
      { id: "pg-1", accountId: "profleet-glendale-2", date: at(0, 9, 15),  type: "visit", title: "Q3 fleet expansion budget confirmed — strong opportunity for an expanded contract", summary: "Q3 fleet expansion discussed. Budget confirmed. Strong opportunity for expanded contract.",         durationMinutes: 45,  hasTranscript: true,  repName: "Jordan Mills" },
      { id: "pg-2", accountId: "profleet-glendale-2", date: at(14, 11, 0), type: "call",  title: "Checked on the outstanding invoice — payment confirmed for this Friday", summary: "Checked on outstanding invoice from last month. Confirmed payment scheduled for this Friday.",       durationMinutes: 10,  hasTranscript: false, repName: "Sarah Kim" },
      { id: "pg-3", accountId: "profleet-glendale-2", date: at(28, 14, 30), type: "visit", title: "Quarterly check-in — team satisfied with current service levels, no open issues", summary: "Standard quarterly check-in. No major issues. Team satisfied with current service levels.",          durationMinutes: 30,  hasTranscript: true,  repName: "Sarah Kim" },
    ],
  },
  "innovative-tech-tucson": {
    ...mockAccounts[8],
    relatedAccountCount: 2,
    lastVisitSummary:
      "Visited 30 days ago. Sandra mentioned the team has been evaluating three vendors — we're the frontrunner. Budget is approved. Main concern is implementation timeline.",
    ideasForThisTime: [
      "Present implementation timeline to address concerns",
      "Offer a phased rollout option",
      "Introduce Sandra to our customer success lead",
      "Ask about any remaining internal stakeholders to align",
    ],
    actionItems: [
      { id: "it-t1", title: "Share implementation timeline",    dueDate: future(6, 2),  status: "open", originActivity: "Vendor Review", originActivityId: "it-1" },
      { id: "it-t2", title: "Intro call with CS lead",          dueDate: future(6, 9),  status: "open", originActivity: "Vendor Review", originActivityId: "it-1" },
      { id: "it-t3", title: "On-site training for new team",    dueDate: null,          status: "open", originActivity: "Vendor Review", originActivityId: "it-1" },
      { id: "it-t4", title: "Send phased rollout options doc",  dueDate: future(6, 6),  status: "open", originActivity: "Vendor Review", originActivityId: "it-1" },
    ],
    recentActivity: [
      { id: "it-1", accountId: "innovative-tech-tucson", date: at(30, 10, 0),  type: "visit", title: "Sandra confirmed we're the frontrunner in their vendor eval — timeline is the sticking point", summary: "Sandra shared that we're the frontrunner in their vendor evaluation. Budget approved, timeline is key concern.", durationMinutes: 50,  hasTranscript: true,  repName: "Jordan Mills" },
      { id: "it-2", accountId: "innovative-tech-tucson", date: at(45, 15, 30), type: "call",  title: "Mapped out current workflows and pain points with their existing parts solution", summary: "Initial discovery to understand current workflows and pain points with existing solution.", durationMinutes: 35,  hasTranscript: true,  repName: "Jordan Mills" },
      { id: "it-3", accountId: "innovative-tech-tucson", date: at(60, 9, 0),   type: "visit", title: "First in-person with Sandra and two department leads — very positive reception", summary: "First in-person visit. Met with Sandra and two department leads. Very positive reception.", durationMinutes: 60,  hasTranscript: false, repName: "Jordan Mills" },
    ],
  },
  "profleet-flagstaff": {
    ...mockAccounts[5],
    relatedAccountCount: 14,
    lastVisitSummary:
      "Visited 3 weeks ago. Toured the facility and met the new ops manager. Team is settling in well — discussed Q3 service needs and flagged some potential volume growth.",
    ideasForThisTime: [
      "Follow up on Q3 service volume estimate",
      "Introduce volume discount options",
      "Check in on the new ops manager's onboarding",
      "Confirm any outstanding support tickets",
    ],
    actionItems: [
      { id: "pf-flag-t1", title: "Send Q3 service estimate",    dueDate: future(6, 10), status: "open", originActivity: "On-site Visit", originActivityId: "pf-flagstaff-1" },
      { id: "pf-flag-t2", title: "Follow up with ops manager",  dueDate: future(6, 14), status: "open", originActivity: "On-site Visit", originActivityId: "pf-flagstaff-1" },
      { id: "pf-flag-t3", title: "Submit volume discount sheet", dueDate: future(6, 20), status: "open", originActivity: "On-site Visit", originActivityId: "pf-flagstaff-1" },
    ],
    recentActivity: [
      { id: "pf-flagstaff-1", accountId: "profleet-flagstaff", date: at(4, 10, 45), type: "visit", title: "Toured the Flagstaff facility and met the new ops manager — Q3 service needs discussed", summary: "Toured the Flagstaff facility and met the new ops manager. Discussed Q3 service needs and potential volume growth.", durationMinutes: 64, hasTranscript: true, repName: "Alex Chen" },
      { id: "pf-flagstaff-2", accountId: "profleet-flagstaff", date: at(25, 14, 0), type: "call",  title: "First call with incoming ops manager ahead of the site visit — aligned on open items", summary: "First call with the incoming ops manager ahead of the on-site visit. Aligned on expectations and open items.", durationMinutes: 20, hasTranscript: false, repName: "Alex Chen" },
    ],
  },
  "riverbend-collision": {
    ...mockAccounts[9],
    relatedAccountCount: 1,
    lastVisitSummary:
      "Last visited over a year ago. Tom was friendly but noncommittal — mentioned they'd been getting by with their current setup. Re-engagement should focus on what's changed in their business.",
    ideasForThisTime: [
      "Ask what's changed in their business since last visit",
      "Lead with new product improvements since last conversation",
      "Offer a no-pressure demo of the latest service tier",
      "Reconnect with Tom personally before pitching anything",
    ],
    actionItems: [
      { id: "rb-t1", title: "Send re-engagement email", dueDate: future(6, 5),  status: "open", originActivity: "Re-engagement Visit", originActivityId: "rb-1" },
      { id: "rb-t2", title: "Schedule demo call",       dueDate: future(6, 18), status: "open", originActivity: "Re-engagement Visit", originActivityId: "rb-1" },
    ],
    recentActivity: [
      { id: "rb-1", accountId: "riverbend-collision", date: at(365, 14, 0), type: "visit", title: "Reconnected with Tom after a long gap — not ready to move but open to staying in touch", summary: "Reconnected with Tom after a long gap. Friendly conversation — not ready to move, but open to staying in touch.", durationMinutes: 25, hasTranscript: false, repName: "Jordan Mills" },
      { id: "rb-2", accountId: "riverbend-collision", date: at(400, 10, 30), type: "call", title: "Tom mentioned they expanded their service bays — flagged as a potential upsell opportunity", summary: "Brief check-in. Tom mentioned they recently expanded their service bays — potential upsell opportunity.", durationMinutes: 12, hasTranscript: false, repName: "Jordan Mills" },
    ],
  },
  "sys-happily-ever-after": {
    id: "sys-happily-ever-after",
    name: "Happily Ever After LLC",
    type: "standalone",
    crmAccountType: "prospect",
    distanceMiles: 3.2,
    lastVisited: daysAgo(18),
    taskCount: 2,
    city: "St. George",
    state: "UT",
    contactName: "Dana Whitfield",
    contactTitle: "Owner",
    crmId: "SF-113",
    relatedAccountCount: 0,
    lastVisitSummary:
      "Stopped in unannounced while in the area. Dana was between events but gave me 20 minutes. They manage a large fleet of catering vans and party vehicles — currently buying supplies through a local distributor with inconsistent pricing. She seemed genuinely interested but wants to see numbers before committing to any conversation.",
    ideasForThisTime: [
      "Come in with a side-by-side comparison on pricing vs. their current supplier",
      "Ask how many vehicles they're running and what the service intervals look like",
      "Find out if Dana is the only decision maker or if there's a business partner involved",
      "Mention the fleet account tier — volume discounts could be a real hook here",
    ],
    actionItems: [
      { id: "hea-t1", title: "Send fleet pricing comparison",       dueDate: future(6, 10), status: "open", originActivity: "Drop-In Visit", originActivityId: "hea-1" },
      { id: "hea-t2", title: "Follow up with Dana on Q3 volume",    dueDate: future(6, 18), status: "open", originActivity: "Drop-In Visit", originActivityId: "hea-1" },
      { id: "hea-t3", title: "Confirm number of vehicles in fleet", dueDate: null,          status: "open", originActivity: "Drop-In Visit", originActivityId: "hea-1" },
    ],
    recentActivity: [
      {
        id: "hea-1", accountId: "sys-happily-ever-after", date: at(18, 14, 30), type: "visit",
        title: "Drop-In Visit",
        summary: "Unannounced drop-in while passing through. Met Dana, the owner. Fleet of catering and event vehicles — real opportunity if pricing holds up. Not a current customer.",
        durationMinutes: 22, hasTranscript: false, repName: "Jordan Mills",
      },
      {
        id: "hea-2", accountId: "sys-happily-ever-after", date: at(22, 10, 0), type: "call",
        title: "Intro Call",
        summary: "Cold outreach. Dana picked up — was friendly but noncommittal. Agreed to an in-person visit when a rep was in the area.",
        durationMinutes: 8, hasTranscript: false, repName: "Jordan Mills",
      },
    ],
  },
  "southwestern-consolidated": {
    ...mockAccounts.find(a => a.id === "southwestern-consolidated")!,
    relatedAccountCount: 6,
    lastVisitSummary:
      "Visited 2 weeks ago. Patricia walked me through their regional fleet footprint — 400+ vehicles across 3 states. They're actively evaluating new parts suppliers after a rough Q1 with their current vendor.",
    ideasForThisTime: [
      "Ask about their Q3 restocking schedule",
      "Pitch the vendor-managed inventory model",
      "Get intro to their procurement lead",
      "Confirm decision timeline before end of quarter",
    ],
    actionItems: [
      { id: "swc-t1", title: "Send regional coverage map", dueDate: future(7, 20), status: "open", originActivity: "Site Visit", originActivityId: "swc-1" },
      { id: "swc-t2", title: "Draft VMI proposal",         dueDate: future(7, 28), status: "open", originActivity: "Site Visit", originActivityId: "swc-1" },
    ],
    recentActivity: [
      {
        id: "swc-1", accountId: "southwestern-consolidated", date: at(14, 10, 30), type: "visit",
        title: "Patricia outlined fleet footprint and flagged Q1 supplier failures as a breaking point",
        summary: "On-site with Patricia Delgado. 400+ vehicles across AZ, NV, and NM. Q1 parts delays caused 3 fleet groundings. They're now actively shopping for a new primary parts supplier.",
        durationMinutes: 65, hasTranscript: true, repName: "Jordan Mills",
        aiSummary: {
          title: "400-vehicle fleet actively switching suppliers after Q1 parts failures — strong opportunity",
          tldr: "Sat down with Patricia and two members of her fleet ops team at their Phoenix HQ. Three fleet groundings in Q1 due to delayed parts have made switching suppliers a board-level priority. Patricia has budget authority and a tight decision window — they want a new vendor locked in before Q3 peak.",
          keyPoints: [
            "**400+ vehicles** across Arizona, Nevada, and New Mexico — one of the largest regional fleets we've engaged.",
            "**3 fleet groundings in Q1** caused by parts delays — Patricia described this as a 'breaking point' with their current vendor.",
            "Board has **approved a vendor switch** and Patricia has budget authority up to $2M annually.",
            "Decision needs to be made **before July 31** to align with Q3 fleet maintenance cycle.",
            "Strong interest in **vendor-managed inventory** — they want to stop holding large safety stock in-house.",
          ],
        },
      },
    ],
  },
};
