import type { Account, AccountDetail } from "@/lib/types";

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);

export const mockAccounts: Account[] = [
  {
    id: "walmart-corp",
    name: "Walmart",
    type: "corporate",
    city: "Bentonville",
    state: "AR",
    distanceMiles: 56.7,
    lastVisited: daysAgo(3),
    childCount: 14,
    crmId: "SF-001",
    healthScore: 82,
  },
  {
    id: "walmart-cedar-city",
    name: "Branch of Walmart",
    type: "branch",
    city: "Cedar City",
    state: "UT",
    distanceMiles: 56.7,
    lastVisited: daysAgo(3),
    childCount: 7,
    parentId: "walmart-corp",
    crmId: "SF-002",
    healthScore: 78,
  },
  {
    id: "jacks-tire-elko",
    name: "Jack's Tire & Oil",
    type: "standalone",
    city: "Elko",
    state: "NV",
    distanceMiles: 13.5,
    lastVisited: daysAgo(14),
    contactName: "Marcus Webb",
    contactTitle: "General Manager",
    crmId: "SF-003",
    healthScore: 65,
  },
  {
    id: "profleet-corp",
    name: "ProFleet Maintenance",
    type: "corporate",
    city: "Phoenix",
    state: "AZ",
    distanceMiles: 146,
    lastVisited: daysAgo(6),
    childCount: 14,
    crmId: "SF-004",
    healthScore: 74,
  },
  {
    id: "profleet-glendale-1",
    name: "ProFleet Maintenance",
    type: "branch",
    city: "Glendale",
    state: "AZ",
    distanceMiles: 0.75,
    lastVisited: daysAgo(90),
    parentId: "profleet-corp",
    crmId: "SF-005",
    healthScore: 55,
  },
  {
    id: "profleet-flagstaff",
    name: "ProFleet Maintenance Store",
    type: "branch",
    city: "Flagstaff",
    state: "AZ",
    distanceMiles: 845,
    lastVisited: daysAgo(21),
    parentId: "profleet-corp",
    crmId: "SF-006",
    healthScore: 70,
  },
  {
    id: "profleet-glendale-2",
    name: "ProFleet Maintenance Store",
    type: "branch",
    city: "Glendale",
    state: "AZ",
    distanceMiles: 3.5,
    lastVisited: new Date(),
    parentId: "profleet-corp",
    crmId: "SF-007",
    healthScore: 88,
  },
  {
    id: "profleet-tucson",
    name: "ProFleet Maintenance Store",
    type: "branch",
    city: "Tucson",
    state: "AZ",
    distanceMiles: 56.7,
    lastVisited: daysAgo(14),
    parentId: "profleet-corp",
    crmId: "SF-008",
    healthScore: 72,
  },
  {
    id: "innovative-tech-tucson",
    name: "Innovative Tech",
    type: "standalone",
    city: "Tucson",
    state: "AZ",
    distanceMiles: 75.2,
    lastVisited: daysAgo(30),
    contactName: "Sandra Perez",
    contactTitle: "Operations Director",
    crmId: "SF-009",
    healthScore: 60,
  },
  {
    id: "riverbend-collision",
    name: "Riverbend Collision",
    type: "standalone",
    city: "St George",
    state: "UT",
    distanceMiles: 241,
    lastVisited: daysAgo(365),
    contactName: "Tom Hadley",
    contactTitle: "Owner",
    crmId: "SF-010",
    healthScore: 30,
  },
];

export const mockAccountDetails: Record<string, AccountDetail> = {
  "walmart-corp": {
    ...mockAccounts[0],
    relatedAccountCount: 24,
    lastVisitSummary:
      "Visited 2 weeks ago. Recent conversation focused on current service satisfaction and day-to-day operational needs. No major issues surfaced.",
    ideasForThisTime: [
      "Ask about upcoming seasonal demand",
      "Explore additional product/service needs",
      "Identify front-line decision makers",
      "Confirm any pain points before they grow",
    ],
    recentActivity: [
      {
        id: "act-1",
        accountId: "walmart-corp",
        date: daysAgo(3),
        type: "visit",
        summary: "Discussed Q2 supply chain concerns. Tom mentioned potential for expanded order next quarter.",
        hasTranscript: true,
        repName: "Jordan Mills",
      },
      {
        id: "act-2",
        accountId: "walmart-corp",
        date: daysAgo(17),
        type: "visit",
        summary: "Routine check-in. Reviewed current service satisfaction. No new opportunities surfaced.",
        hasTranscript: true,
        repName: "Jordan Mills",
      },
      {
        id: "act-3",
        accountId: "walmart-corp",
        date: daysAgo(31),
        type: "call",
        summary: "Follow-up call on delayed shipment. Issue resolved. Customer satisfied.",
        hasTranscript: false,
        repName: "Jordan Mills",
      },
    ],
  },
  "profleet-glendale-2": {
    ...mockAccounts[6],
    relatedAccountCount: 14,
    lastVisitSummary:
      "Visited today. Discussed new fleet acquisition coming in Q3. Manager hinted at budget availability for expanded service contract.",
    ideasForThisTime: [
      "Follow up on Q3 fleet expansion proposal",
      "Introduce premium service tier options",
      "Ask about satisfaction with current turnaround times",
      "Check on status of pending invoice from last month",
    ],
    recentActivity: [
      {
        id: "act-4",
        accountId: "profleet-glendale-2",
        date: new Date(),
        type: "visit",
        summary: "Q3 fleet expansion discussed. Budget confirmed. Strong opportunity for expanded contract.",
        hasTranscript: true,
        repName: "Jordan Mills",
      },
    ],
  },
};
