/**
 * Mock system-wide accounts — these exist in the CRM but are NOT assigned
 * to the current rep. Returned by the "Search all Halosight accounts" flow.
 *
 * In production this would be an API call against the full Salesforce org.
 */

import type { Account } from "@/lib/types";

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 24 * 60 * 60 * 1000);

/** Full rep names keyed by account id — shown as "Assigned to ___" */
export const systemAccountReps: Record<string, string> = {
  "sys-happily-ever-after":   "Marcus W.",
  "sys-big-o-reno":         "Sarah K.",
  "sys-napa-elko":          "Sarah K.",
  "sys-oreilly-wendover":   "Sarah K.",
  "sys-jiffy-sparks":       "Derek M.",
  "sys-autozone-henderson": "Derek M.",
  "sys-firestone-ogden":    "Lisa T.",
  "sys-midas-provo":        "Lisa T.",
  "sys-carquest-moab":      "Lisa T.",
  "sys-speedco-barstow":    "Carlos R.",
  "sys-loves-kingman":      "Carlos R.",
  "sys-fleet-pride-boise":  "Carlos R.",
  "sys-valvoline-flagstaff":"Tara H.",
  "sys-mesa-auto-parts":    "Derek M.",
  "sys-mesa-fleet-services":"Lisa T.",
  "sys-mesa-tire-lube":     "Carlos R.",
  "sys-mesa-truck-center":  "Tara H.",
};

export const mockSystemAccounts: Account[] = [
  {
    id: "sys-happily-ever-after",
    name: "Happily Ever After LLC",
    type: "standalone",
    crmAccountType: "prospect",
    assignedInitial: "M",
    taskCount: 0,
    city: "Tucson",
    state: "AZ",
    distanceMiles: 3.2,
    lastVisited: daysAgo(999),
    crmId: "SF-113",
    healthScore: 0,
  },
  {
    id: "sys-big-o-reno",
    name: "Big O Tires",
    type: "standalone",
    crmAccountType: "sold-to",
    assignedInitial: "S",
    taskCount: 0,
    city: "Reno",
    state: "NV",
    distanceMiles: 89.4,
    lastVisited: daysAgo(12),
    contactName: "Phil Garner",
    contactTitle: "Store Manager",
    crmId: "SF-101",
    healthScore: 71,
  },
  {
    id: "sys-napa-elko",
    name: "NAPA Auto Parts",
    type: "standalone",
    crmAccountType: "sold-to",
    assignedInitial: "S",
    taskCount: 0,
    city: "Elko",
    state: "NV",
    distanceMiles: 14.1,
    lastVisited: daysAgo(45),
    contactName: "Ray Hoffmann",
    contactTitle: "Owner",
    crmId: "SF-102",
    healthScore: 68,
  },
  {
    id: "sys-oreilly-wendover",
    name: "O'Reilly Auto Parts",
    type: "standalone",
    crmAccountType: "shipped-to",
    assignedInitial: "S",
    taskCount: 0,
    city: "Wendover",
    state: "NV",
    distanceMiles: 48.7,
    lastVisited: daysAgo(60),
    crmId: "SF-103",
    healthScore: 55,
  },
  {
    id: "sys-jiffy-sparks",
    name: "Jiffy Lube",
    type: "standalone",
    crmAccountType: "prospect",
    assignedInitial: "D",
    taskCount: 0,
    city: "Sparks",
    state: "NV",
    distanceMiles: 96.2,
    lastVisited: daysAgo(180),
    contactName: "Kim Breslin",
    contactTitle: "Franchise Owner",
    crmId: "SF-104",
    healthScore: 40,
  },
  {
    id: "sys-autozone-henderson",
    name: "AutoZone",
    type: "standalone",
    crmAccountType: "sold-to",
    assignedInitial: "D",
    taskCount: 0,
    city: "Henderson",
    state: "NV",
    distanceMiles: 372,
    lastVisited: daysAgo(8),
    crmId: "SF-105",
    healthScore: 80,
  },
  {
    id: "sys-firestone-ogden",
    name: "Firestone Complete Auto Care",
    type: "standalone",
    crmAccountType: "sold-to",
    assignedInitial: "L",
    taskCount: 0,
    city: "Ogden",
    state: "UT",
    distanceMiles: 211,
    lastVisited: daysAgo(22),
    contactName: "Brenda Yates",
    contactTitle: "Service Manager",
    crmId: "SF-106",
    healthScore: 77,
  },
  {
    id: "sys-midas-provo",
    name: "Midas Auto Service",
    type: "standalone",
    crmAccountType: "sold-to",
    assignedInitial: "L",
    taskCount: 0,
    city: "Provo",
    state: "UT",
    distanceMiles: 245,
    lastVisited: daysAgo(30),
    crmId: "SF-107",
    healthScore: 62,
  },
  {
    id: "sys-carquest-moab",
    name: "CarQuest Auto Parts",
    type: "standalone",
    crmAccountType: "shipped-to",
    assignedInitial: "L",
    taskCount: 0,
    city: "Moab",
    state: "UT",
    distanceMiles: 318,
    lastVisited: daysAgo(90),
    crmId: "SF-108",
    healthScore: 50,
  },
  {
    id: "sys-speedco-barstow",
    name: "Speedco Truck Lube & Tires",
    type: "standalone",
    crmAccountType: "sold-to",
    assignedInitial: "C",
    taskCount: 0,
    city: "Barstow",
    state: "CA",
    distanceMiles: 484,
    lastVisited: daysAgo(14),
    crmId: "SF-109",
    healthScore: 73,
  },
  {
    id: "sys-loves-kingman",
    name: "Love's Truck Care",
    type: "standalone",
    crmAccountType: "distributor",
    assignedInitial: "C",
    taskCount: 0,
    city: "Kingman",
    state: "AZ",
    distanceMiles: 194,
    lastVisited: daysAgo(5),
    crmId: "SF-110",
    healthScore: 85,
  },
  {
    id: "sys-fleet-pride-boise",
    name: "FleetPride",
    type: "standalone",
    crmAccountType: "distributor",
    assignedInitial: "C",
    taskCount: 0,
    city: "Boise",
    state: "ID",
    distanceMiles: 412,
    lastVisited: daysAgo(7),
    contactName: "Greg Fosse",
    contactTitle: "District Manager",
    crmId: "SF-111",
    healthScore: 88,
  },
  {
    id: "sys-valvoline-flagstaff",
    name: "Valvoline Instant Oil Change",
    type: "standalone",
    crmAccountType: "prospect",
    assignedInitial: "T",
    taskCount: 0,
    city: "Flagstaff",
    state: "AZ",
    distanceMiles: 276,
    lastVisited: daysAgo(999),
    crmId: "SF-112",
    healthScore: 0,
  },
  {
    id: "sys-mesa-auto-parts",
    name: "Mesa Auto Parts",
    type: "standalone",
    crmAccountType: "sold-to",
    assignedInitial: "D",
    taskCount: 0,
    city: "Mesa",
    state: "AZ",
    distanceMiles: 8.4,
    lastVisited: daysAgo(21),
    crmId: "SF-114",
    healthScore: 66,
  },
  {
    id: "sys-mesa-fleet-services",
    name: "Mesa Fleet Services",
    type: "standalone",
    crmAccountType: "distributor",
    assignedInitial: "L",
    taskCount: 0,
    city: "Mesa",
    state: "AZ",
    distanceMiles: 9.1,
    lastVisited: daysAgo(55),
    crmId: "SF-115",
    healthScore: 74,
  },
  {
    id: "sys-mesa-tire-lube",
    name: "Mesa Tire & Lube",
    type: "standalone",
    crmAccountType: "prospect",
    assignedInitial: "C",
    taskCount: 0,
    city: "Mesa",
    state: "AZ",
    distanceMiles: 11.3,
    lastVisited: daysAgo(120),
    crmId: "SF-116",
    healthScore: 42,
  },
  {
    id: "sys-mesa-truck-center",
    name: "Mesa Truck Center",
    type: "standalone",
    crmAccountType: "sold-to",
    assignedInitial: "T",
    taskCount: 0,
    city: "Mesa",
    state: "AZ",
    distanceMiles: 12.7,
    lastVisited: daysAgo(8),
    crmId: "SF-117",
    healthScore: 81,
  },
];
